[project]
name = "PancreasMRISegmentation"
version = "0.1.0"
description = "Comprehensive analysis of state-of-the-art deep learning solutions for pancreas MRI segmentation, including architectures, datasets, evaluation metrics, and current limitations."
authors = [
    {name = "ms-Ana", email = "ms.urmanana@gmail.com"},
]
dependencies = ["nnunet>=1.7.1", 
"nnunetv2>=2.6.2", 
"torch==2.10.0", 
"click>=8.3.1", 
"gdown>=5.2.1"
]
requires-python = "<3.15,>=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[tool.pdm]
distribution = true

[project.scripts]
custom_nnUNetv2_predict_from_modelfolder = "pancreasmrisegmentation.run.predict_from_raw_data:predict_entry_point_modelfolder"