datasets:
  panther:
    path: /home/anastasiia/MasterThesis/external_data/Imaging/Panther
    labels: /home/anastasiia/MasterThesis/external_data/Imaging/Panther/nnUNet_raw/Dataset090_PantherTask1/labelsTr
    
  # amos22:
  #   path: /home/anastasiia/MasterThesis/external_data/Imaging/AMOS22/imagesVa
  #   labels: /home/anastasiia/MasterThesis/external_data/Imaging/AMOS22/labelsVa
    
  # mrisegmenter:
  #   path: /home/anastasiia/MasterThesis/external_data/Imaging/MRISegmenter/ImageTs
  #   labels: /home/anastasiia/MasterThesis/external_data/Imaging/MRISegmenter/labelsTs
    
  # totalsegmentator:
  #   path: 
  #   labels:
    
    # pansegnet_t2:
    #   path: /home/anastasiia/MasterThesis/external_data/Imaging/PanSegData/Pancreas_MRI_Dataset/t2/imagesTr
    #   labels: /home/anastasiia/MasterThesis/external_data/Imaging/PanSegData/Pancreas_MRI_Dataset/t2/labelsTr
  
models:

  umamba_nnunet:
  umamba_swinunetr:
  umamba_segresnet: 
  umamba_bot:
  umamba_enc:

  total_segmentator:

  mri_segmenter:


  mr_segmentator:

  pansegnet_t1:
  pansegnet_t2:


  voxtell:

  # mri_segmenter0:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/mri_segmenter0
  #   predictor: nnUNetv2
  #   label: 11

  # mri_segmenter1:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/mri_segmenter1
  #   predictor: nnUNetv2
  #   label: 11

  # mri_segmenter2:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/mri_segmenter2
  #   predictor: nnUNetv2
  #   label: 11 

  # mri_segmenter3:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/mri_segmenter3
  #   predictor: nnUNetv2
  #   label: 11 

  # mri_segmenter4:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/mri_segmenter4
  #   predictor: nnUNetv2
  #   label: 11

  # mr_segmentator0:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/mr_segmentator0
  #   predictor: nnUNetv2
  #   label: 7

  # mr_segmentator1:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/mr_segmentator1
  #   predictor: nnUNetv2
  #   label: 7

  # mr_segmentator2:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/mr_segmentator2
  #   predictor: nnUNetv2
  #   label: 7

  # mr_segmentator3:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/mr_segmentator3
  #   predictor: nnUNetv2
  #   label: 7

  # mr_segmentator4:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/mr_segmentator4
  #   predictor: nnUNetv2
  #   label: 7
    

  
  # staple_top_3_total:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/staple/amos22_top_3_total
  #   predictor: staple
  #   label: 1
  staple_mri_segmenter:
    path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/staple/panther_mri_segmenter
    predictor: staple
    label: 1
  # staple_top_2:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/staple/pansegnet_t2_top_2
  #   predictor: staple
  #   label: 1
  # staple_top_4:
  #   path: /home/anastasiia/MasterThesis/PancreasMRISegmentation/results1/staple/amos22_top_4
  #   predictor: staple
  #   label: 1

device: cuda